#!/bin/bash
#/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome $* 2>&1 &
#/Applications/Chromium.app/Contents/MacOS/Chromium $* 2>&1 &
# /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --profile-directory="Default" $* 2>&1 &

/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --new-window --args --profile-directory="Default" $* 2>&1 &
## [REF] https://superuser.com/questions/731467/command-line-option-to-open-chrome-in-new-window-and-move-focus
